title: My Personal Portfolio Website
description: Development of my personal portfolio website and associated GitHub Project Pages
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
repository: thanhxtruong/personal-portfolio
